[env:esp32-s3-devkitc-1]
extra_scripts = pre:../shared/can/pio_prebuild.py
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.flash_mode = dio
board_build.f_cpu = 240000000L

build_flags =
    -std=gnu++17
    -Wno-error
    -D CONFIG_FREERTOS_HZ=1000
    -D CONFIG_TWAI_ISR_IN_IRAM=1
    -I ../shared
build_unflags = -Werror
