[platformio]
default_envs = twai

[env:twai]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.flash_mode = dio
build_src_filter = +<main.cpp> -<spi_test.cpp>

build_flags =
    -std=gnu++17
    -Wno-error

[env:spi]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.flash_mode = dio
build_src_filter = +<spi_test.cpp> -<main.cpp>

build_flags =
    -std=gnu++17
    -Wno-error
