#!/usr/bin/env python3
"""Generate the PWT powertrain CAN contract from can_powertrain.yaml."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "can_powertrain.yaml"
OUTPUT = ROOT / "src" / "generated" / "pwt_can_data.h"


def load_contract() -> dict:
    data = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    if data.get("bus", {}).get("bitrate_hz") != 250_000:
        raise ValueError("powertrain bitrate_hz must be 250000")
    messages = data.get("messages", [])
    if len(messages) != 1:
        raise ValueError("PWT currently supports exactly one manufacturer command")
    message = messages[0]
    can_id = int(message["id"], 0) if isinstance(message["id"], str) else message["id"]
    if not message.get("extended") or not 0x800 <= can_id <= 0x1FFFFFFF:
        raise ValueError("PWT_DCDC_CMD must use a valid 29-bit extended CAN ID")
    if message.get("dlc") != 8 or message.get("cycle_ms") != 100:
        raise ValueError("PWT_DCDC_CMD must be DLC 8 at a 100 ms cycle")
    return data


def generate(data: dict) -> str:
    message = data["messages"][0]
    can_id = int(message["id"], 0) if isinstance(message["id"], str) else message["id"]
    digest = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()
    return f"""// GENERATED by pwt-esp32/generate_can.py — DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>

namespace pwt::can_data {{
constexpr char kProtocolHash[] = \"{digest}\";
constexpr int kBitrateHz = {data['bus']['bitrate_hz']};
constexpr uint32_t kIdDcdcCmd = 0x{can_id:08X};
constexpr bool kDcdcCmdExtended = true;
constexpr uint8_t kDlcDcdcCmd = {message['dlc']};
constexpr int kDcdcCmdCycleMs = {message['cycle_ms']};
constexpr uint8_t kDcdcEnable = 0x01;
constexpr uint8_t kDcdcDisable = 0x00;
constexpr uint8_t kDcdcNoReset = 0x00;
constexpr uint8_t kDcdcReset = 0x01;
constexpr uint8_t kDcdcReserved = 0xFF;

enum class CodecStatus : uint8_t {{
    Ok = 0, NullBuffer = 1, BufferTooSmall = 2,
    ValueOutOfRange = 6, InvalidEnum = 7, ConstantMismatch = 8
}};

struct DcdcCmd {{
    static constexpr uint32_t kId = kIdDcdcCmd;
    static constexpr uint8_t kDlc = kDlcDcdcCmd;
    static constexpr bool kExtended = true;
    bool enabled{{true}};
    bool reset{{false}};

    CodecStatus pack(uint8_t* dst, size_t len) const noexcept {{
        if (!dst) return CodecStatus::NullBuffer;
        if (len < kDlc) return CodecStatus::BufferTooSmall;
        dst[0] = enabled ? kDcdcEnable : kDcdcDisable;
        for (size_t i = 1; i <= 6; ++i) dst[i] = kDcdcReserved;
        dst[7] = reset ? kDcdcReset : kDcdcNoReset;
        return CodecStatus::Ok;
    }}

    static CodecStatus unpack(const uint8_t* src, size_t len, DcdcCmd& out) noexcept {{
        if (!src) return CodecStatus::NullBuffer;
        if (len < kDlc) return CodecStatus::BufferTooSmall;
        if (src[0] > kDcdcEnable || src[7] > kDcdcReset) return CodecStatus::InvalidEnum;
        for (size_t i = 1; i <= 6; ++i)
            if (src[i] != kDcdcReserved) return CodecStatus::ConstantMismatch;
        DcdcCmd value{{}};
        value.enabled = src[0] == kDcdcEnable;
        value.reset = src[7] == kDcdcReset;
        out = value;
        return CodecStatus::Ok;
    }}
}};
}} // namespace pwt::can_data
"""


def main() -> int:
    content = generate(load_contract())
    if "--verify" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"MISMATCH: {OUTPUT}; run pwt-esp32/generate_can.py")
            return 1
        print("PWT CAN contract verified")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
