[platformio]
default_envs = vehicle

[env:vehicle]
extra_scripts = pre:../protocol/tools/pio_prebuild_canonical.py
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -I ..
    -D CONFIG_TWAI_ISR_IN_IRAM=1
    -D FW_VERSION="v0.4.0-alpha-vehicle"

[env:bench]
extra_scripts = pre:../protocol/tools/pio_prebuild_canonical.py
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -I ..
    -D CONFIG_TWAI_ISR_IN_IRAM=1
    -D BENCH_BUILD_ACKNOWLEDGED
    -D FW_VERSION="v0.4.0-alpha-bench"
