#pragma once
// CAN gateway forwarding policy — pure, deterministic.
// Category 1: transparent forward (same ID, same payload).
// Category 2: consumed by RT -> different message generated.
// Category 3: bus-local (never forwarded, never regenerated).
//
// The wire catalogs (bus membership) live here; the actual byte forwarding
// is applied by the gateway controller using the route decision.

#include <cstdint>

namespace rta {

// Logical CAN buses.
enum class Bus : std::uint8_t { Low = 0, High = 1 };

constexpr const char* bus_name(Bus b) noexcept {
    return b == Bus::Low ? "low" : "high";
}

// Which direction a message flows for the gateway.
enum class RouteAction : std::uint8_t {
    ForwardLowToHigh,   // Category 1: L2H transparent
    ForwardHighToLow,   // Category 1: H2L transparent
    ConsumeAndRegenerate, // Category 2: RT consumes, emits derived frame(s)
    BusLocal,           // Category 3: never forwarded
};

// Route decision for a received CAN ID.
struct RouteDecision {
    RouteAction action;
    bool        is_estop = false;  // ESTOP uses urgent TxClass + rate limiting
};

// Classify a received frame by its CAN ID. The gateway controller calls
// this on RX and applies the result.
inline RouteDecision classify_route(Bus rx_bus, std::uint32_t can_id) noexcept {
    // ESTOP (0x001) is bridged in both directions.
    if (can_id == 0x001u) {
        return {rx_bus == Bus::Low ? RouteAction::ForwardLowToHigh
                                   : RouteAction::ForwardHighToLow,
                true};
    }
    // Category 1 low->high transparent: MTR speed/feedback.
    if (rx_bus == Bus::Low &&
        (can_id == 0x120u || can_id == 0x206u)) {
        return {RouteAction::ForwardLowToHigh, false};
    }
    // Category 1 high->low transparent: host lights.
    if (rx_bus == Bus::High && can_id == 0x302u) {
        return {RouteAction::ForwardHighToLow, false};
    }
    // Category 2: consumed by RT -> derived frames generated by the
    // orchestrator (0x300 -> 0x204 + 0x169; 0x301 -> 0x7B9; 0x303 -> 0x169).
    if (rx_bus == Bus::High &&
        (can_id == 0x300u || can_id == 0x301u || can_id == 0x303u)) {
        return {RouteAction::ConsumeAndRegenerate, false};
    }
    // Everything else is bus-local (RT telemetry, actuator feedback/status,
    // HMI requests consumed locally, etc.).
    return {RouteAction::BusLocal, false};
}

}  // namespace rta
