[platformio]
default_envs = vehicle

[env:vehicle]
extra_scripts = pre:../protocol/tools/pio_prebuild_canonical.py
platform = ststm32
platform_packages =
    toolchain-gccarmnoneeabi@~1.100301.0
board = genericSTM32G431CB
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink

build_flags =
    -std=gnu++17
    -O2
    -Wno-error
    -D STM32G431xx
    -D USE_HAL_DRIVER
    -I Core/Inc
    -I src
    -I ..
    -I ../shared

build_src_filter =
    +<../src/*.cpp>
    +<../Core/Src/stm32g4xx_it.c>
    +<../Core/Src/stm32g4xx_hal_msp.c>
    +<../Core/Src/system_stm32g4xx.c>
    +<../Core/Src/syscalls.c>
    +<../Core/Src/sysmem.c>
    +<../Core/Startup/startup_stm32g431cbux.s>
