[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
monitor_speed = 115200

build_flags =
    -std=gnu++17
    -Wno-error
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -I ../shared
build_unflags = -Werror
