[platformio]
default_envs = vehicle

[env:vehicle]
platform = ststm32
platform_packages = toolchain-gccarmnoneeabi@1.100301.220327
board = genericSTM32F103C8
framework = stm32cube
monitor_speed = 115200
build_src_filter = +<main.cpp> -<native_entry.cpp>

build_flags =
    -std=gnu++17
    -Wno-error
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -D FW_VERSION="v0.3.0-alpha-vehicle"
    -I ..
    -I ../shared
build_unflags = -Werror

[env:bench]
platform = ststm32
platform_packages = toolchain-gccarmnoneeabi@1.100301.220327
board = genericSTM32F103C8
framework = stm32cube
monitor_speed = 115200
build_src_filter = +<main.cpp> -<native_entry.cpp>

build_flags =
    -std=gnu++17
    -Wno-error
    -D USE_HAL_DRIVER
    -D STM32F103xB
    -D BENCH_BUILD_ACKNOWLEDGED
    -D FW_VERSION="v0.3.0-alpha-bench"
    -I ..
    -I ../shared
build_unflags = -Werror

[env:native]
platform = native
build_src_filter = +<native_entry.cpp>
build_flags =
    -std=gnu++17
    -Wno-error
    -mconsole
    -I ..
    -I ../shared
