"""Generate frame-independent, status-returning C++ CAN payload codecs."""

from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass

from can_signals_schema import network_contract_hash, wire_protocol_hash


def snake(name: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name.replace("-", "_"))
    return re.sub(r"_+", "_", value).strip("_").lower()


def pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:].lower() for part in re.split(r"_+", name) if part)


def cpp_type(sig) -> str:
    if sig.size == 1 or (sig.min == 0 and sig.max == 1 and sig.size <= 8):
        return "bool"
    width = 8 if sig.size <= 8 else 16 if sig.size <= 16 else 32 if sig.size <= 32 else 64
    return f"{'int' if sig.type.value == 'signed' else 'uint'}{width}_t"


def raw_bounds(sig) -> tuple[int, int]:
    storage_min = -(1 << (sig.size - 1)) if sig.type.value == "signed" else 0
    storage_max = (1 << (sig.size - (1 if sig.type.value == "signed" else 0))) - 1
    if sig.factor == 0:
        return storage_min, storage_max
    minimum = math.ceil((float(sig.min) - sig.offset) / sig.factor)
    maximum = math.floor((float(sig.max) - sig.offset) / sig.factor)
    return max(storage_min, minimum), min(storage_max, maximum)


@dataclass(frozen=True)
class Entry:
    protocol: str
    bus: str
    byte_order: str
    message: object


def unique_messages(db) -> list[Entry]:
    result: list[Entry] = []
    seen: set[str] = set()
    for protocol_name, protocol in db.protocols.items():
        for message in protocol.messages:
            if message.name in seen:
                continue
            seen.add(message.name)
            result.append(Entry(protocol_name, protocol.bus, protocol.byte_order.value, message))
    return result


def _enum_check(member: str, sig, indent: str) -> list[str]:
    if not sig.values or sig.unit != "enum":
        return []
    conditions = " && ".join(f"{member} != {value}" for value in sorted(sig.values))
    return [f"{indent}if ({conditions}) return CodecStatus::InvalidEnum;"]


def generate_cpp_codecs(db) -> str:
    lines = ["""// GENERATED by shared/can/generate_code.py — DO NOT EDIT.
#pragma once
#include <cstddef>
#include <cstdint>
#include <cmath>

namespace can::gen {

enum class CodecStatus : uint8_t {
    Ok = 0,
    NullBuffer = 1,
    BufferTooSmall = 2,
    UnexpectedLength = 3,
    WrongMessageId = 4,
    WrongFrameFormat = 5,
    ValueOutOfRange = 6,
    InvalidEnum = 7,
    ConstantMismatch = 8,
    ChecksumMismatch = 9,
};

inline constexpr const char* codec_status_name(CodecStatus status) noexcept {
    switch (status) {
        case CodecStatus::Ok: return "CAN_CODEC_OK";
        case CodecStatus::NullBuffer: return "CAN_CODEC_NULL_BUFFER";
        case CodecStatus::BufferTooSmall: return "CAN_CODEC_BUFFER_TOO_SMALL";
        case CodecStatus::UnexpectedLength: return "CAN_CODEC_UNEXPECTED_LENGTH";
        case CodecStatus::WrongMessageId: return "CAN_CODEC_WRONG_MESSAGE_ID";
        case CodecStatus::WrongFrameFormat: return "CAN_CODEC_WRONG_FRAME_FORMAT";
        case CodecStatus::ValueOutOfRange: return "CAN_CODEC_VALUE_OUT_OF_RANGE";
        case CodecStatus::InvalidEnum: return "CAN_CODEC_INVALID_ENUM";
        case CodecStatus::ConstantMismatch: return "CAN_CODEC_CONSTANT_MISMATCH";
        case CodecStatus::ChecksumMismatch: return "CAN_CODEC_CHECKSUM_MISMATCH";
    }
    return "CAN_CODEC_UNKNOWN";
}

namespace detail {
inline uint64_t extract(const uint8_t* src, size_t byte, uint8_t bit, uint8_t size,
                        bool little) noexcept {
    if (little) {
        uint64_t value = 0;
        for (uint8_t i = 0; i < size; ++i) {
            const size_t absolute = byte * 8u + bit + i;
            value |= uint64_t((src[absolute / 8u] >> (absolute % 8u)) & 1u) << i;
        }
        return value;
    }
    if (bit + size <= 8) return (src[byte] >> bit) & ((uint64_t{1} << size) - 1u);
    uint64_t value = 0;
    const size_t count = size / 8u;
    for (size_t i = 0; i < count; ++i) value = (value << 8u) | src[byte + i];
    return value;
}

inline void insert(uint8_t* dst, size_t byte, uint8_t bit, uint8_t size,
                   bool little, uint64_t value) noexcept {
    if (little) {
        for (uint8_t i = 0; i < size; ++i) {
            const size_t absolute = byte * 8u + bit + i;
            const uint8_t mask = uint8_t(1u << (absolute % 8u));
            dst[absolute / 8u] = uint8_t((dst[absolute / 8u] & ~mask) |
                (((value >> i) & 1u) ? mask : 0u));
        }
        return;
    }
    if (bit + size <= 8) {
        const uint8_t mask = uint8_t(((uint64_t{1} << size) - 1u) << bit);
        dst[byte] = uint8_t((dst[byte] & ~mask) | ((value << bit) & mask));
        return;
    }
    const size_t count = size / 8u;
    for (size_t i = 0; i < count; ++i)
        dst[byte + count - 1u - i] = uint8_t(value >> (i * 8u));
}

inline int64_t sign_extend(uint64_t value, uint8_t bits) noexcept {
    if (bits == 64) return static_cast<int64_t>(value);
    const uint64_t sign = uint64_t{1} << (bits - 1u);
    return static_cast<int64_t>((value ^ sign) - sign);
}
} // namespace detail
"""]
    for entry in unique_messages(db):
        msg = entry.message
        type_name = pascal(msg.name)
        lines += [f"\nstruct {type_name} {{",
                  f"    static constexpr uint32_t kId = 0x{msg.id:X}u;",
                  f"    static constexpr size_t kDlc = {msg.dlc}u;",
                  "    static constexpr bool kExtended = false;"]
        member_names: set[str] = set()
        members: list[tuple[str, object]] = []
        for sig in msg.signals:
            member = snake(sig.key or sig.name)
            if member in member_names:
                member = snake(sig.name)
            member_names.add(member)
            members.append((member, sig))
            lines.append(f"    {cpp_type(sig)} {member}{{}};")
        lines += ["", "    CodecStatus pack(uint8_t* dst, size_t len) const noexcept {",
                  "        if (!dst && kDlc != 0) return CodecStatus::NullBuffer;",
                  "        if (len < kDlc) return CodecStatus::BufferTooSmall;"]
        for member, sig in members:
            lo, hi = raw_bounds(sig)
            if cpp_type(sig) != "bool":
                condition = f"{member} > {hi}" if lo == 0 and cpp_type(sig).startswith("uint") else f"{member} < {lo} || {member} > {hi}"
                lines.append(f"        if ({condition}) return CodecStatus::ValueOutOfRange;")
            lines += _enum_check(member, sig, "        ")
        lines += ["        for (size_t i = 0; i < kDlc; ++i) dst[i] = 0;",
                  f"        constexpr bool little = {'true' if entry.byte_order == 'intel' else 'false'};"]
        for member, sig in members:
            value = f"static_cast<uint64_t>({member})"
            lines.append(f"        detail::insert(dst, {sig.byte}u, {sig.bit_offset}u, {sig.size}u, little, {value});")
        lines += ["        return CodecStatus::Ok;", "    }", "",
                  f"    static CodecStatus unpack(const uint8_t* src, size_t len, {type_name}& out) noexcept {{",
                  "        if (!src && kDlc != 0) return CodecStatus::NullBuffer;",
                  "        if (len < kDlc) return CodecStatus::BufferTooSmall;",
                  f"        {type_name} value{{}};",
                  f"        constexpr bool little = {'true' if entry.byte_order == 'intel' else 'false'};"]
        for member, sig in members:
            raw = f"detail::extract(src, {sig.byte}u, {sig.bit_offset}u, {sig.size}u, little)"
            if cpp_type(sig) == "bool":
                lines.append(f"        const auto raw_{member} = {raw};")
                lines.append(f"        if (raw_{member} > 1u) return CodecStatus::ValueOutOfRange;")
                expression = f"(raw_{member} != 0)"
            elif sig.type.value == "signed":
                expression = f"static_cast<{cpp_type(sig)}>(detail::sign_extend({raw}, {sig.size}u))"
            else:
                expression = f"static_cast<{cpp_type(sig)}>({raw})"
            lines.append(f"        value.{member} = {expression};")
            lo, hi = raw_bounds(sig)
            if cpp_type(sig) != "bool":
                condition = f"value.{member} > {hi}" if lo == 0 and cpp_type(sig).startswith("uint") else f"value.{member} < {lo} || value.{member} > {hi}"
                lines.append(f"        if ({condition}) return CodecStatus::ValueOutOfRange;")
            lines += _enum_check(f"value.{member}", sig, "        ")
        lines += ["        out = value;", "        return CodecStatus::Ok;", "    }"]
        for member, sig in members:
            if sig.factor != 1.0 or sig.offset != 0.0:
                fn = pascal(member)
                lo, hi = raw_bounds(sig)
                lines += [f"    static constexpr double {member}_to_physical({cpp_type(sig)} raw) noexcept {{",
                          f"        return static_cast<double>(raw) * {sig.factor!r} + {sig.offset!r};", "    }",
                          f"    static CodecStatus {member}_from_physical(double physical, {cpp_type(sig)}& raw) noexcept {{",
                          f"        const auto candidate = static_cast<int64_t>(std::llround((physical - {sig.offset!r}) / {sig.factor!r}));",
                          f"        if (candidate < {lo} || candidate > {hi}) return CodecStatus::ValueOutOfRange;",
                          f"        raw = static_cast<{cpp_type(sig)}>(candidate);",
                          "        return CodecStatus::Ok;", "    }"]
        lines.append("};")
    lines += [f'\ninline constexpr char kWireProtocolHash[] = "{wire_protocol_hash(db)}";',
              f'inline constexpr char kNetworkContractHash[] = "{network_contract_hash(db)}";',
              "\n} // namespace can::gen\n"]
    return "\n".join(lines)


def generate_codec_manifest(db) -> str:
    messages = []
    for entry in unique_messages(db):
        msg = entry.message
        messages.append({
            "key": snake(msg.name), "type": pascal(msg.name), "id": f"0x{msg.id:X}",
            "bus": entry.bus, "dlc": msg.dlc, "extended": False,
            "byte_order": entry.byte_order,
            "class": "event" if not msg.signals else
                     "stateful" if any((s.key or "").endswith("counter") or "alive" in (s.key or "") for s in msg.signals) else
                     "packed" if any(s.size == 1 or s.bit_offset for s in msg.signals) else "simple",
        })
    return json.dumps({"wire_protocol_hash": wire_protocol_hash(db),
                       "network_contract_hash": network_contract_hash(db),
                       "messages": messages}, indent=2) + "\n"


def generate_error_registry() -> str:
    values = [
        (0, "CAN_CODEC_OK", "Operation succeeded"),
        (1, "CAN_CODEC_NULL_BUFFER", "Payload buffer is null"),
        (2, "CAN_CODEC_BUFFER_TOO_SMALL", "Payload buffer is shorter than the message DLC"),
        (3, "CAN_CODEC_UNEXPECTED_LENGTH", "Received DLC does not match the contract"),
        (4, "CAN_CODEC_WRONG_MESSAGE_ID", "Frame ID does not match the requested message"),
        (5, "CAN_CODEC_WRONG_FRAME_FORMAT", "Standard or extended frame format does not match"),
        (6, "CAN_CODEC_VALUE_OUT_OF_RANGE", "Signal raw value is outside its declared range"),
        (7, "CAN_CODEC_INVALID_ENUM", "Signal contains an undeclared enum value"),
        (8, "CAN_CODEC_CONSTANT_MISMATCH", "Reserved or constant bits do not match"),
        (9, "CAN_CODEC_CHECKSUM_MISMATCH", "Vendor checksum validation failed"),
    ]
    return json.dumps({"errors": [{"id": i, "name": n, "message": m} for i, n, m in values]}, indent=2) + "\n"
