#!/usr/bin/env python3
"""
Generate shared CAN data files from YAML — single source of truth.

Reads can_high.yaml + can_low.yaml, produces:
  shared/can/generated/can_ids.ts        — TypeScript CAN catalog
  shared/can/generated/can_constants.ts  — TypeScript shared constants
  shared/can/generated/can_data.h        — C++ constexpr header

Usage:
  python generate_code.py                # generate all 3 files
  python generate_code.py --verify       # check generated files match YAML
"""

import sys
import os
from pathlib import Path
from datetime import datetime
from can_signals_schema import load_can_database_dir

CAN_DIR = Path(__file__).resolve().parent
GEN_DIR = CAN_DIR / "generated"
TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

HEADER_TS = f"""// GENERATED by shared/can/generate_code.py — DO NOT EDIT.
// Source: shared/can/can_high.yaml + shared/can/can_low.yaml
// Generated: {TIMESTAMP}

"""

HEADER_CPP = f"""// GENERATED by shared/can/generate_code.py — DO NOT EDIT.
// Source: shared/can/can_high.yaml + shared/can/can_low.yaml
// Generated: {TIMESTAMP}

#pragma once
#include <cstdint>

"""


def to_hex(n: int) -> str:
    return f"0x{n:03X}"


def ts_const_name(can_id: int, name: str) -> str:
    """Generate a TypeScript constant name from CAN message name."""
    return f"ID_{name}"


def cpp_const_name(can_id: int, name: str) -> str:
    """Generate a C++ constant name from CAN message name."""
    return f"kId{name.replace('_', '')}"


def generate_can_ids_ts(db) -> str:
    """Generate TypeScript CAN IDs, DLCs, bus, names, signals, forwarding."""
    lines = [HEADER_TS]

    # Build message catalog
    all_msgs = []  # (bus, msg, protocol_name)
    for pname, proto in db.protocols.items():
        bus = proto.bus if proto.bus in ("high", "low") else "low"
        for msg in proto.messages:
            all_msgs.append((bus, msg, pname))

    # ── CAN ID constants ─────────────────────────────────────────
    lines.append("// ── CAN ID constants ─────────────────────────────────────")
    seen = set()
    for bus, msg, pname in sorted(all_msgs, key=lambda x: x[1].id):
        if msg.id in seen:
            continue
        seen.add(msg.id)
        cname = ts_const_name(msg.id, msg.name)
        lines.append(f"export const {cname} = {to_hex(msg.id)};")
    lines.append(f"// {len(seen)} unique IDs")
    lines.append("")

    # ── DLC table ────────────────────────────────────────────────
    lines.append("// ── DLC table (CAN ID → expected byte count) ──────────────")
    lines.append("export const DLC: Record<string, number> = {")
    seen = set()
    for bus, msg, pname in sorted(all_msgs, key=lambda x: x[1].id):
        key = to_hex(msg.id)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f'  "{key}": {msg.dlc},  // {msg.name}')
    lines.append("};")
    lines.append("")

    # ── Bus assignment ──────────────────────────────────────────
    lines.append("// ── Bus assignment ────────────────────────────────────────")
    lines.append("export const BUS: Record<string, \"high\" | \"low\" | \"both\"> = {")
    seen_low = set()
    seen_high = set()
    for bus, msg, pname in all_msgs:
        if bus == "high":
            seen_high.add(msg.id)
        else:
            seen_low.add(msg.id)
    for mid in sorted(seen_high | seen_low):
        key = to_hex(mid)
        on_low = mid in seen_low
        on_high = mid in seen_high
        bus_val = '"both"' if on_low and on_high else ('"high"' if on_high else '"low"')
        lines.append(f'  "{key}": {bus_val},')
    lines.append("};")
    lines.append("")

    # ── Message names ───────────────────────────────────────────
    lines.append("// ── Message names ──────────────────────────────────────────")
    lines.append("export const NAME: Record<string, string> = {")
    seen = set()
    for bus, msg, pname in sorted(all_msgs, key=lambda x: x[1].id):
        key = to_hex(msg.id)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f'  "{key}": "{msg.name}",')
    lines.append("};")
    lines.append("")

    # ── Sender ──────────────────────────────────────────────────
    lines.append("// ── Sender ─────────────────────────────────────────────────")
    lines.append("export const SENDER: Record<string, string> = {")
    seen = set()
    for bus, msg, pname in sorted(all_msgs, key=lambda x: x[1].id):
        key = to_hex(msg.id)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f'  "{key}": "{msg.sender}",')
    lines.append("};")
    lines.append("")

    # ── Cycle rates ─────────────────────────────────────────────
    lines.append("// ── Cycle rates (ms) ───────────────────────────────────────")
    lines.append("export const CYCLE_MS: Record<string, number> = {")
    seen = set()
    for bus, msg, pname in sorted(all_msgs, key=lambda x: x[1].id):
        key = to_hex(msg.id)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f'  "{key}": {msg.cycle_ms},  // {msg.name}')
    lines.append("};")
    lines.append("")

    # ── Enum value tables ───────────────────────────────────────
    lines.append("// ── Enum value tables ──────────────────────────────────────")
    lines.append("export const MODE_VALUES: Record<number, string> = {0:\"Manual\", 1:\"Auto\", 2:\"ESTOP\"};")
    lines.append("export const GEAR_VALUES: Record<number, string> = {0:\"N\", 1:\"D\", 2:\"S\", 3:\"R\"};")
    lines.append("")

    # ── Forwarding rules ───────────────────────────────────────
    # Find messages appearing on both buses
    high_ids = {msg.id for bus, msg, _ in all_msgs if bus == "high"}
    low_ids = {msg.id for bus, msg, _ in all_msgs if bus == "low"}
    fwd_low_to_high = sorted(low_ids & high_ids)
    lines.append("// ── Gateway forwarding rules ────────────────────────────────")
    lines.append("// Messages forwarded low→high by RT (transparent copy)")
    lines.append(f"export const FWD_LOW_TO_HIGH: number[] = {[hex(x) for x in fwd_low_to_high]};")
    lines.append(f"export const FWD_HIGH_TO_LOW: number[] = {[hex(x) for x in fwd_low_to_high]};")
    lines.append("// (Same set — bidirectional forwarding for these IDs)")
    lines.append("")

    # ── Signal definitions (compact) ────────────────────────────
    lines.append("// ── Signal byte layouts ─────────────────────────────────────")
    lines.append("export interface SignalDef { byte: number; bit_offset: number; size: number;")
    lines.append("  type?: string; factor?: number; offset?: number; unit?: string;")
    lines.append("  values?: Record<number,string>; }")
    lines.append("export const SIG: Record<string, Record<string, SignalDef>> = {")
    seen_sig = set()
    for bus, msg, pname in sorted(all_msgs, key=lambda x: x[1].id):
        if not msg.signals:
            continue
        key = to_hex(msg.id)
        if key in seen_sig:
            continue  # forwarded frame — same signals on both buses, keep first only
        seen_sig.add(key)
        lines.append(f'  "{key}": {{  // {msg.name} ({bus} bus)')
        for sig in msg.signals:
            fields = [f"byte:{sig.byte}", f"bit_offset:{sig.bit_offset}", f"size:{sig.size}"]
            if sig.type and sig.type.value != "unsigned":
                fields.append(f'type:"{sig.type.value}"')
            if sig.factor != 1.0:
                fields.append(f"factor:{sig.factor}")
            if sig.offset != 0.0:
                fields.append(f"offset:{sig.offset}")
            if sig.unit:
                fields.append(f'unit:"{sig.unit}"')
            if sig.values:
                vals = ",".join(f"{k}:'{v}'" for k, v in sorted(sig.values.items()))
                fields.append(f"values:{{{vals}}}")
            lines.append(f'    {sig.name}: {{{", ".join(fields)}}},')
        lines.append("  },")
    lines.append("};")

    return "\n".join(lines) + "\n"


def generate_can_constants_ts(db) -> str:
    """Generate TypeScript constants from YAML constants section."""
    lines = [HEADER_TS]
    lines.append("// ── Shared constants from can_high.yaml ────────────────────")
    lines.append("")

    consts = db.constants
    for key, val in sorted(consts.items()):
        ts_name = key.upper()
        if isinstance(val, float):
            lines.append(f"export const {ts_name} = {val};")
        elif isinstance(val, bool):
            lines.append(f"export const {ts_name} = {'true' if val else 'false'};")
        else:
            lines.append(f"export const {ts_name} = {val};")

    return "\n".join(lines) + "\n"


def generate_can_data_h(db) -> str:
    """Generate C++ header with CAN IDs, DLCs, constants."""
    lines = [HEADER_CPP]
    lines.append("namespace can::data {")
    lines.append("")

    # CAN ID constants
    lines.append("// ── CAN ID constants ────────────────────────────────────")
    seen = set()
    for pname, proto in db.protocols.items():
        for msg in proto.messages:
            if msg.id in seen:
                continue
            seen.add(msg.id)
            cname = cpp_const_name(msg.id, msg.name)
            lines.append(f"constexpr uint16_t {cname} = {to_hex(msg.id)};  // {msg.name}")
    lines.append("")

    # DLC values
    lines.append("// ── DLC values (per CAN ID) ─────────────────────────────")
    seen = set()
    for pname, proto in db.protocols.items():
        for msg in proto.messages:
            if msg.id in seen:
                continue
            seen.add(msg.id)
            lines.append(f"constexpr uint8_t kDlc_{msg.name} = {msg.dlc};")
    lines.append("")

    # Shared constants
    lines.append("// ── Shared constants ─────────────────────────────────────")
    consts = db.constants
    for key, val in sorted(consts.items()):
        cpp_name = "k" + "".join(w.capitalize() for w in key.split("_"))
        if isinstance(val, float):
            lines.append(f"constexpr float {cpp_name} = {val}f;")
        elif isinstance(val, bool):
            lines.append(f"constexpr bool {cpp_name} = {'true' if val else 'false'};")
        else:
            lines.append(f"constexpr int {cpp_name} = {val};")
    lines.append("")

    lines.append("} // namespace can::data")
    return "\n".join(lines) + "\n"


def main():
    do_verify = "--verify" in sys.argv

    db = load_can_database_dir(CAN_DIR)
    print(f"Loaded: {len(db.protocols)} protocols, {len(db.ecus)} ECUs, {len(db.constants)} constants")

    # Generate TypeScript
    ts_ids = generate_can_ids_ts(db)
    ts_consts = generate_can_constants_ts(db)
    cpp_h = generate_can_data_h(db)

    if do_verify:
        # Compare generated with existing files
        errors = []
        for fname, content in [
            ("can_ids.ts", ts_ids),
            ("can_constants.ts", ts_consts),
            ("can_data.h", cpp_h),
        ]:
            fpath = GEN_DIR / fname
            if not fpath.exists():
                errors.append(f"MISSING: {fpath}")
                continue
            existing = fpath.read_text(encoding="utf-8")
            # Compare ignoring the timestamp line
            existing_lines = existing.split("\n")
            new_lines = content.split("\n")
            # Skip timestamp lines (line 3 in each header)
            existing_no_ts = [l for l in existing_lines if "Generated:" not in l]
            new_no_ts = [l for l in new_lines if "Generated:" not in l]
            if existing_no_ts != new_no_ts:
                errors.append(f"MISMATCH: {fpath} differs from generated output")
                # Show first difference
                for i, (e, n) in enumerate(zip(existing_no_ts, new_no_ts)):
                    if e != n:
                        errors.append(f"  Line {i+1}: expected {n[:80]!r}")
                        errors.append(f"  Line {i+1}: got      {e[:80]!r}")
                        break
                if len(existing_no_ts) != len(new_no_ts):
                    errors.append(f"  Line count: existing={len(existing_no_ts)}, generated={len(new_no_ts)}")

        if errors:
            print("\nVERIFY FAILED:")
            for e in errors:
                print(f"  {e}")
            print("\nRun 'python generate_code.py' to regenerate.")
            sys.exit(1)
        else:
            print("VERIFY PASSED — all generated files match YAML.")
            sys.exit(0)

    # Write generated files
    os.makedirs(GEN_DIR, exist_ok=True)
    for fname, content in [
        ("can_ids.ts", ts_ids),
        ("can_constants.ts", ts_consts),
        ("can_data.h", cpp_h),
    ]:
        fpath = GEN_DIR / fname
        fpath.write_text(content, encoding="utf-8")
        print(f"  Wrote {fpath} ({len(content)} bytes)")

    print(f"\nDone: 3 files generated in {GEN_DIR}")


if __name__ == "__main__":
    main()
