#!/usr/bin/env python3
"""Generate the debug-tool TypeScript CAN index from shared/can/*.yaml."""

from __future__ import annotations

from pathlib import Path
import json

from can_signals_schema import load_can_database_dir


CAN_DIR = Path(__file__).resolve().parent
OUT_FILE = CAN_DIR.parent.parent / "debug-tool" / "ui" / "src" / "lib" / "can-index.ts"


def fmt_id(value: int) -> str:
    return f"0x{value:03X}"


def main() -> int:
    db = load_can_database_dir(CAN_DIR)
    messages = []

    for protocol_name, protocol in db.protocols.items():
        bus = protocol.bus or ("low" if "low" in protocol_name else "high")
        for message in protocol.messages:
            messages.append({
                "bus": bus,
                "id": fmt_id(message.id),
                "name": message.name,
                "dlc": message.dlc,
                "sender": message.sender,
                "receivers": message.receivers,
                "cycle_ms": message.cycle_ms,
                "comment": message.comment,
                "byte_order": protocol.byte_order.value,
                "protocol": protocol_name,
                "signals": [
                    {
                        "name": signal.name,
                        "byte": signal.byte,
                        "bit_offset": signal.bit_offset,
                        "size": signal.size,
                        "type": signal.type.value,
                        "factor": signal.factor,
                        "offset": signal.offset,
                        "min": signal.min,
                        "max": signal.max,
                        "unit": signal.unit,
                        "receivers": signal.receivers,
                        "values": signal.values,
                        "comment": signal.comment,
                    }
                    for signal in message.signals
                ],
            })

    messages.sort(key=lambda item: (item["bus"], int(item["id"], 16), item["name"]))

    payload = json.dumps(messages, indent=2, ensure_ascii=False)
    content = f"""// Generated by shared/can/generate_can_index.py. Do not edit manually.

import type {{ Bus }} from "./can-decoder";

export type CanByteOrder = "motorola" | "intel";
export type CanSignalType = "signed" | "unsigned";

export interface CanSignalDef {{
  name: string;
  byte: number;
  bit_offset: number;
  size: number;
  type: CanSignalType;
  factor: number;
  offset: number;
  min: number | null;
  max: number | null;
  unit: string;
  receivers: string[];
  values: Record<string, string> | null;
  comment: string;
}}

export interface CanMessageIndex {{
  bus: Bus;
  id: string;
  name: string;
  dlc: number;
  sender: string;
  receivers: string[];
  cycle_ms: number;
  comment: string;
  byte_order: CanByteOrder;
  protocol: string;
  signals: CanSignalDef[];
}}

export const CAN_INDEX: CanMessageIndex[] = {payload} as CanMessageIndex[];
"""

    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(CAN_DIR.parent.parent)} ({len(messages)} messages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
